version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_project
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      # Syncs your local code to the container instantly
      - .:/app